plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
}

android {
    compileSdk 34

    defaultConfig {
        applicationId "com.codergang.directchat"
        minSdk 23
        targetSdk 34
        versionCode 6
        versionName "1.0.6"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        viewBinding true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    namespace 'com.codergang.directchat'
}

dependencies {

    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation "androidx.fragment:fragment-ktx:1.6.1"
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.6.2'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.2'
    def lifecycle_version = "2.6.2"
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-process:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-common-java8:$lifecycle_version"

    //CCP
    implementation 'com.hbb20:ccp:2.5.4'

    //ADS
    implementation 'com.google.android.gms:play-services-ads:22.4.0'

    //Room
    implementation 'androidx.room:room-runtime:2.5.2'
    kapt "androidx.room:room-compiler:2.5.2"
    implementation "android.arch.persistence.room:runtime:1.1.1"
    annotationProcessor 'androidx.room:room-compiler:2.5.2'
    implementation "androidx.room:room-ktx:2.5.2"

    //QR
    implementation 'com.github.SumiMakito:AwesomeQRCode:1.2.0'
    implementation "com.waynejo:androidndkgif:0.3.3"

    //Splash Screen
    implementation 'androidx.core:core-splashscreen:1.0.1'

    def retrofit_version = "2.9.0"
    implementation "com.squareup.retrofit2:converter-gson:$retrofit_version"

    //Indicator
    implementation 'com.tbuonomo:dotsindicator:4.2'
}